package ClientCommands.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ClientCommand = 0;
  public static final int CommandListVersion = 1;
  public static final int CommandVersionPool = 2;
  public static final int ServerCommand = 3;
  public static final int ServerCommandClearCanvas = 4;
  public static final int ServerCommandDrawPath = 5;
  public static final int StringConstant = 6;
  public static final int StringParameter = 7;
  public static final int StringValue = 8;
  public static final int StringValueReference = 9;
  public static final int StringValueTraits = 10;
  public static final int Value = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x803175666604ec4L, 0x9045cc3f1cabfba1L);
    builder.put(0x2615a4c93fb9ae0eL, ClientCommand);
    builder.put(0x2615a4c93fb84420L, CommandListVersion);
    builder.put(0x7fc1c94250b16ef7L, CommandVersionPool);
    builder.put(0x2615a4c93fb9789dL, ServerCommand);
    builder.put(0x2615a4c93fb9ae40L, ServerCommandClearCanvas);
    builder.put(0x2615a4c93fb978a0L, ServerCommandDrawPath);
    builder.put(0x2615a4c93fb9ae13L, StringConstant);
    builder.put(0x2615a4c93fb9ae14L, StringParameter);
    builder.put(0x2615a4c93fb9ae12L, StringValue);
    builder.put(0x2615a4c93fc158adL, StringValueReference);
    builder.put(0x7fc1c94251143092L, StringValueTraits);
    builder.put(0x2615a4c93fb9ae1eL, Value);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
