package de.janradeck.svgclient;

/*Generated by MPS */


public class testClient {
  private InjectionFactoryClient factory;
  public testClient(InjectionFactoryClient factory) {
    this.factory = factory;
  }

  public void drawGreenV1(String message, String path) {
    QueryGenerator query = factory.getQueryGenerator("/v1/drawGreen");
    query.addParameter("message", message);
    query.addParameter("path", path);
    query.executeGetQuery();
  }
  public void drawBlackV1(String message, String path) {
    QueryGenerator query = factory.getQueryGenerator("/v1/drawBlack");
    query.addParameter("message", message);
    query.addParameter("path", path);
    query.executeGetQuery();
  }
  public void clearV1() {
    QueryGenerator query = factory.getQueryGenerator("/v1/clear");
    query.executeGetQuery();
  }
  public void drawRectV1() {
    QueryGenerator query = factory.getQueryGenerator("/v1/drawRect");
    query.executeGetQuery();
  }
  public void simpleDrawV1() {
    QueryGenerator query = factory.getQueryGenerator("/v1/simpleDraw");
    query.executeGetQuery();
  }
  public void drawLightBlueV2(String message, String path) {
    QueryGenerator query = factory.getQueryGenerator("/v2/drawLightBlue");
    query.addParameter("message", message);
    query.addParameter("path", path);
    query.executeGetQuery();
  }
  public void clearV2() {
    QueryGenerator query = factory.getQueryGenerator("/v2/clear");
    query.executeGetQuery();
  }


}
